// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vnes_core_top.h for the primary calling header

#ifndef VERILATED_VNES_CORE_TOP_NES_H_
#define VERILATED_VNES_CORE_TOP_NES_H_  // guard

#include "verilated.h"
class Vnes_core_top_APU__Sz1_SBz2_SCz3_SDz4;
class Vnes_core_top_CODES;
class Vnes_core_top_ClockGen;
class Vnes_core_top_DmaController;
class Vnes_core_top_PPU;
class Vnes_core_top_T65;
class Vnes_core_top_cart_top;
class Vnes_core_top_eReg_SavestateV__Az5;
class Vnes_core_top_savestates;
class Vnes_core_top_statemanager__pi1;


class Vnes_core_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vnes_core_top_NES final {
  public:
    // CELLS
    Vnes_core_top_ClockGen* __PVT__clockgen_pause;
    Vnes_core_top_T65* __PVT__cpu;
    Vnes_core_top_DmaController* __PVT__dma;
    Vnes_core_top_APU__Sz1_SBz2_SCz3_SDz4* __PVT__apu;
    Vnes_core_top_PPU* __PVT__ppu;
    Vnes_core_top_cart_top* __PVT__multi_mapper;
    Vnes_core_top_CODES* __PVT__codes;
    Vnes_core_top_eReg_SavestateV__Az5* __PVT__iREG_SAVESTATE_TOP;
    Vnes_core_top_savestates* __PVT__savestates;
    Vnes_core_top_statemanager__pi1* __PVT__statemanager;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ __PVT__clk;
        CData/*0:0*/ __PVT__reset_nes;
        CData/*0:0*/ __PVT__ppu_rst_behavior;
        CData/*0:0*/ __PVT__cold_reset;
        CData/*0:0*/ __PVT__pausecore;
        CData/*0:0*/ __PVT__corepaused;
        CData/*1:0*/ __PVT__sys_type;
        CData/*1:0*/ __PVT__nes_div;
        CData/*5:0*/ __PVT__color;
        CData/*1:0*/ __PVT__joypad_clock;
        CData/*2:0*/ __PVT__joypad_out;
        CData/*4:0*/ __PVT__joypad1_data;
        CData/*4:0*/ __PVT__joypad2_data;
        CData/*0:0*/ __PVT__fds_busy;
        CData/*0:0*/ __PVT__fds_eject;
        CData/*0:0*/ __PVT__fds_auto_eject;
        CData/*1:0*/ __PVT__max_diskside;
        CData/*0:0*/ __PVT__fds_fast;
        CData/*1:0*/ __PVT__diskside;
        CData/*4:0*/ __PVT__audio_channels;
        CData/*0:0*/ __PVT__ex_sprites;
        CData/*1:0*/ __PVT__mask;
        CData/*0:0*/ __PVT__dejitter_timing;
        CData/*0:0*/ __PVT__cpumem_read;
        CData/*0:0*/ __PVT__cpumem_write;
        CData/*7:0*/ __PVT__cpumem_dout;
        CData/*7:0*/ __PVT__cpumem_din;
        CData/*0:0*/ __PVT__ppumem_read;
        CData/*0:0*/ __PVT__ppumem_write;
        CData/*7:0*/ __PVT__ppumem_dout;
        CData/*7:0*/ __PVT__ppumem_din;
        CData/*0:0*/ __PVT__refresh;
        CData/*7:0*/ __PVT__bram_din;
        CData/*7:0*/ __PVT__bram_dout;
        CData/*0:0*/ __PVT__bram_write;
        CData/*0:0*/ __PVT__bram_override;
        CData/*0:0*/ __PVT__int_audio;
        CData/*0:0*/ __PVT__ext_audio;
        CData/*0:0*/ __PVT__apu_ce;
        CData/*0:0*/ __PVT__gg;
        CData/*0:0*/ __PVT__gg_avail;
        CData/*0:0*/ __PVT__gg_reset;
        CData/*2:0*/ __PVT__emphasis;
        CData/*0:0*/ __PVT__save_written;
        CData/*0:0*/ __PVT__mapper_has_flashsaves;
        CData/*0:0*/ __PVT__debug_dots;
        CData/*0:0*/ __PVT__mapper_has_savestate;
        CData/*0:0*/ __PVT__increaseSSHeaderCount;
        CData/*0:0*/ __PVT__save_state;
        CData/*0:0*/ __PVT__load_state;
        CData/*1:0*/ __PVT__savestate_number;
        CData/*0:0*/ __PVT__sleep_savestate;
        CData/*0:0*/ __PVT__state_loaded;
        CData/*0:0*/ __PVT__hsync;
        CData/*0:0*/ __PVT__hblank;
        CData/*0:0*/ __PVT__vsync;
        CData/*0:0*/ __PVT__vblank;
        CData/*0:0*/ __PVT__Savestate_SDRAMRdEn;
        CData/*0:0*/ __PVT__Savestate_SDRAMWrEn;
        CData/*7:0*/ __PVT__Savestate_SDRAMWriteData;
        CData/*7:0*/ __PVT__Savestate_SDRAMReadData;
        CData/*0:0*/ __PVT__SaveStateExt_wren;
        CData/*0:0*/ __PVT__SaveStateExt_rst;
        CData/*0:0*/ __PVT__SaveStateExt_load;
    };
    struct {
        CData/*0:0*/ __PVT__SAVE_out_rnw;
        CData/*0:0*/ __PVT__SAVE_out_ena;
        CData/*7:0*/ __PVT__SAVE_out_be;
        CData/*0:0*/ __PVT__SAVE_out_done;
        CData/*7:0*/ __PVT__from_data_bus;
        CData/*7:0*/ __PVT__cpu_dout;
        CData/*0:0*/ __PVT__odd_or_even;
        CData/*4:0*/ __PVT__div_cpu;
        CData/*2:0*/ __PVT__div_ppu;
        CData/*1:0*/ __PVT__div_sys;
        CData/*0:0*/ __PVT__cpu_ce;
        CData/*0:0*/ __PVT__ppu_ce;
        CData/*0:0*/ __PVT__cart_ce;
        CData/*0:0*/ __PVT__cart_pre;
        CData/*0:0*/ __PVT__ppu_read;
        CData/*0:0*/ __PVT__ppu_write;
        CData/*0:0*/ __PVT__phi2;
        CData/*0:0*/ __PVT__skip_pixel;
        CData/*0:0*/ __PVT__freeze_clocks;
        CData/*4:0*/ __PVT__faux_pixel_cnt;
        CData/*0:0*/ __PVT__use_fake_h;
        CData/*1:0*/ __PVT__ppu_tick;
        CData/*1:0*/ __PVT__last_sys_type;
        CData/*2:0*/ __PVT__cpu_tick_count;
        CData/*0:0*/ __PVT__skip_ppu_cycle;
        CData/*0:0*/ __PVT__hold_reset;
        CData/*0:0*/ __PVT__bootvector_flag;
        CData/*0:0*/ __PVT__cpu_reset;
        CData/*0:0*/ __PVT__reset;
        CData/*0:0*/ __PVT__reset_noSS;
        CData/*0:0*/ __PVT__corepause_active;
        CData/*0:0*/ __PVT__corepause_active_delay;
        CData/*0:0*/ __PVT__skip_pause_ce;
        CData/*7:0*/ __PVT__corepause_delay;
        CData/*2:0*/ __PVT__div_ppu_pause;
        CData/*0:0*/ __PVT__skip_pixel_pause;
        CData/*0:0*/ __PVT__ppu_ce_pause;
        CData/*0:0*/ __PVT__render_ena;
        CData/*0:0*/ __PVT__is_in_vblank_paused;
        CData/*0:0*/ __PVT__evenframe;
        CData/*0:0*/ __PVT__evenframe_paused;
        CData/*0:0*/ __Vcellinp__clockgen_pause__ce;
        CData/*0:0*/ __PVT__cpu_rnw;
        CData/*0:0*/ __PVT__pause_cpu;
        CData/*0:0*/ __PVT__nmi;
        CData/*0:0*/ __PVT__mapper_irq;
        CData/*0:0*/ __PVT__apu_irq;
        CData/*0:0*/ __PVT__cpu_Instrnew;
        CData/*0:0*/ __PVT__apu_reg_cs;
        CData/*7:0*/ __PVT__apu_reg_value;
        CData/*7:0*/ __PVT__internal_data_bus;
        CData/*7:0*/ __Vcellinp__cpu__DI;
        CData/*0:0*/ __Vcellinp__cpu__NMI_n;
        CData/*0:0*/ __Vcellinp__cpu__IRQ_n;
        CData/*0:0*/ __Vcellinp__cpu__rdy;
        CData/*0:0*/ __Vcellinp__cpu__pwr_n;
        CData/*0:0*/ __Vcellinp__cpu__res_n;
        CData/*0:0*/ __PVT__dma_aout_enable;
        CData/*0:0*/ __PVT__dma_read;
        CData/*7:0*/ __PVT__dma_data_to_ram;
        CData/*0:0*/ __PVT__apu_dma_request;
        CData/*0:0*/ __PVT__apu_dma_ack;
        CData/*7:0*/ __PVT__dma_data_bus;
        CData/*7:0*/ __PVT__dbus;
    };
    struct {
        CData/*0:0*/ __PVT__mr_int;
        CData/*0:0*/ __PVT__mw_int;
        CData/*0:0*/ __PVT__get_ce;
        CData/*0:0*/ __PVT__put_ce;
        CData/*0:0*/ __Vcellinp__dma__sprite_trigger;
        CData/*0:0*/ __PVT__apu_cs;
        CData/*7:0*/ __PVT__apu_dout;
        CData/*4:0*/ __Vcellinp__apu__ADDR;
        CData/*0:0*/ __Vcellinp__apu__PAL;
        CData/*1:0*/ __PVT__audio_en;
        CData/*0:0*/ __PVT__joypad1_cs;
        CData/*0:0*/ __PVT__joypad2_cs;
        CData/*2:0*/ __PVT__joy_out;
        CData/*2:0*/ __PVT__joy_latch;
        CData/*0:0*/ __PVT__mr_ppu;
        CData/*0:0*/ __PVT__mw_ppu;
        CData/*0:0*/ __PVT__ppu_cs;
        CData/*7:0*/ __PVT__ppu_dout;
        CData/*0:0*/ __PVT__chr_read;
        CData/*0:0*/ __PVT__chr_write;
        CData/*0:0*/ __PVT__chr_read_ex;
        CData/*7:0*/ __PVT__chr_from_ppu;
        CData/*7:0*/ __PVT__chr_to_ppu;
        CData/*0:0*/ __Vcellinp__ppu__write;
        CData/*0:0*/ __Vcellinp__ppu__read;
        CData/*2:0*/ __Vcellinp__ppu__ain;
        CData/*0:0*/ __Vcellinp__ppu__RWn;
        CData/*0:0*/ __Vcellinp__ppu__cs;
        CData/*7:0*/ __PVT__prg_din;
        CData/*0:0*/ __PVT__prg_read;
        CData/*0:0*/ __PVT__prg_write;
        CData/*0:0*/ __PVT__prg_allow;
        CData/*0:0*/ __PVT__vram_a10;
        CData/*0:0*/ __PVT__vram_ce;
        CData/*0:0*/ __PVT__chr_allow;
        CData/*7:0*/ __PVT__prg_dout_mapper;
        CData/*7:0*/ __PVT__chr_from_ppu_mapper;
        CData/*0:0*/ __PVT__has_chr_from_ppu_mapper;
        CData/*0:0*/ __PVT__prg_bus_write;
        CData/*0:0*/ __PVT__prg_conflict;
        CData/*0:0*/ __PVT__prg_conflict_d0;
        CData/*0:0*/ __PVT__has_flashsaves;
        CData/*0:0*/ __Vcellinp__multi_mapper__ce;
        CData/*0:0*/ __PVT__genie_ovr;
        CData/*7:0*/ __PVT__genie_data;
        CData/*7:0*/ __Vcellinp__codes__data_in;
        CData/*0:0*/ __Vcellinp__codes__enable;
        CData/*7:0*/ __PVT__open_bus_data;
        CData/*7:0*/ __PVT__external_data_bus;
        CData/*0:0*/ __PVT__SaveStateBus_wren;
        CData/*0:0*/ __PVT__SaveStateBus_rst;
        CData/*7:0*/ __PVT__Savestate_RAMWriteData;
        CData/*7:0*/ __PVT__Savestate_RAMReadData;
        CData/*0:0*/ __PVT__Savestate_RAMRdEn;
        CData/*0:0*/ __PVT__Savestate_RAMWrEn;
        CData/*2:0*/ __PVT__Savestate_RAMType;
        CData/*0:0*/ __PVT__reset_ss;
        CData/*0:0*/ __PVT__reset_delay;
        CData/*0:0*/ __PVT__savestate_savestate;
        CData/*0:0*/ __PVT__savestate_loadstate;
        CData/*0:0*/ __PVT__savestate_busy;
        CData/*0:0*/ __PVT__loading_savestate;
        CData/*0:0*/ __PVT__saving_savestate;
        CData/*0:0*/ __PVT__sleep_savestates;
    };
    struct {
        CData/*0:0*/ __PVT__sleep_rewind;
        CData/*7:0*/ __PVT__Savestate_OAMAddr;
        CData/*0:0*/ __PVT__Savestate_OAMRdEn;
        CData/*0:0*/ __PVT__Savestate_OAMWrEn;
        CData/*7:0*/ __PVT__Savestate_OAMWriteData;
        CData/*7:0*/ __PVT__Savestate_OAMReadData;
        CData/*0:0*/ __PVT__Savestate_MAPRAMactive;
        CData/*0:0*/ __PVT__Savestate_MAPRAMRdEn;
        CData/*0:0*/ __PVT__Savestate_MAPRAMWrEn;
        CData/*7:0*/ __PVT__Savestate_MAPRAMWriteData;
        CData/*7:0*/ __PVT__Savestate_MAPRAMReadData;
        CData/*1:0*/ sys_type__en0;
        CData/*1:0*/ sys_type__out;
        CData/*1:0*/ sys_type__en;
        CData/*1:0*/ sys_type__out__strong;
        CData/*1:0*/ sys_type__out__strong__en;
        CData/*1:0*/ sys_type__out__strong__out1;
        CData/*1:0*/ sys_type__out__strong__en1;
        CData/*0:0*/ __Vdly__hold_reset;
        CData/*4:0*/ __Vdly__div_cpu;
        CData/*2:0*/ __Vdly__div_ppu;
        CData/*1:0*/ __Vdly__ppu_tick;
        CData/*2:0*/ __Vdly__cpu_tick_count;
        CData/*1:0*/ __Vdly__div_sys;
        CData/*0:0*/ __Vdly__freeze_clocks;
        CData/*4:0*/ __Vdly__faux_pixel_cnt;
        CData/*0:0*/ __Vdly__bootvector_flag;
        CData/*0:0*/ __Vdly__odd_or_even;
        CData/*1:0*/ __Vdly__last_sys_type;
        CData/*0:0*/ __Vdly__skip_pause_ce;
        CData/*0:0*/ __Vdly__corepause_active;
        CData/*0:0*/ __Vdly__corepause_active_delay;
        CData/*2:0*/ __Vdly__div_ppu_pause;
        CData/*7:0*/ __Vdly__corepause_delay;
        CData/*2:0*/ __Vdly__joy_out;
        CData/*2:0*/ __Vdly__joy_latch;
        CData/*7:0*/ __Vdly__open_bus_data;
        SData/*15:0*/ __PVT__sample;
        SData/*8:0*/ __PVT__cycle;
        SData/*8:0*/ __PVT__scanline;
        SData/*9:0*/ __PVT__SaveStateExt_Adr;
        SData/*8:0*/ __PVT__cycle_paused;
        SData/*8:0*/ __PVT__scanline_paused;
        SData/*15:0*/ __PVT__cpu_addr;
        SData/*15:0*/ __PVT__dma_aout;
        SData/*15:0*/ __PVT__apu_dma_addr;
        SData/*15:0*/ __PVT__addr;
        SData/*15:0*/ __PVT__sample_apu;
        SData/*15:0*/ __PVT__sample_a;
        SData/*15:0*/ __PVT__sample_inverted;
        SData/*15:0*/ __PVT__audio_mappers;
        SData/*13:0*/ __PVT__chr_addr;
        SData/*13:0*/ __PVT__chr_addr_ex;
        SData/*8:0*/ __PVT__ppu_cycle;
        SData/*8:0*/ __PVT__scanline_ppu;
        SData/*15:0*/ __PVT__prg_addr;
        SData/*15:0*/ __PVT__sample_ext;
        SData/*9:0*/ __Vcellinp__multi_mapper__chr_mask;
        SData/*9:0*/ __Vcellinp__multi_mapper__prg_mask;
        SData/*9:0*/ __PVT__SaveStateBus_Adr;
        SData/*12:0*/ __PVT__Savestate_MAPRAMAddr;
        IData/*24:0*/ __PVT__cpumem_addr;
        IData/*21:0*/ __PVT__ppumem_addr;
        IData/*20:0*/ __PVT__prg_mask;
    };
    struct {
        IData/*19:0*/ __PVT__chr_mask;
        IData/*17:0*/ __PVT__bram_addr;
        VlWide<5>/*128:0*/ __PVT__gg_code;
        IData/*24:0*/ __PVT__Savestate_SDRAMAddr;
        IData/*25:0*/ __PVT__SAVE_out_Adr;
        IData/*24:0*/ __PVT__prg_linaddr;
        IData/*21:0*/ __PVT__chr_linaddr;
        IData/*24:0*/ __PVT__Savestate_RAMAddr;
        IData/*31:0*/ __PVT__savestate_address;
        QData/*63:0*/ __PVT__mapper_flags;
        QData/*63:0*/ __PVT__SaveStateExt_Din;
        QData/*63:0*/ __PVT__SaveStateExt_Dout;
        QData/*63:0*/ __PVT__SAVE_out_Din;
        QData/*63:0*/ __PVT__SAVE_out_Dout;
        QData/*63:0*/ __Vcellout__cpu__SaveStateBus_Dout;
        QData/*63:0*/ __Vcellout__apu__SaveStateBus_Dout;
        QData/*63:0*/ __Vcellout__ppu__SaveStateBus_Dout;
        QData/*63:0*/ __Vcellout__multi_mapper__SaveStateBus_Dout;
        QData/*63:0*/ __PVT__SaveStateBus_Din;
        QData/*63:0*/ __PVT__SS_TOP;
        QData/*63:0*/ __PVT__SS_TOP_BACK;
        QData/*63:0*/ __Vcellout__iREG_SAVESTATE_TOP____pinNumber6;
        QData/*63:0*/ __PVT__SaveStateBus_Dout;
        VlUnpacked<QData/*63:0*/, 5> __PVT__SaveStateBus_wired_or;
    };

    // INTERNAL VARIABLES
    Vnes_core_top__Syms* vlSymsp;
    const char* vlNamep;

    // CONSTRUCTORS
    Vnes_core_top_NES();
    ~Vnes_core_top_NES();
    void ctor(Vnes_core_top__Syms* symsp, const char* namep);
    void dtor();
    VL_UNCOPYABLE(Vnes_core_top_NES);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
