// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vnes_core_top.h for the primary calling header

#ifndef VERILATED_VNES_CORE_TOP___024ROOT_H_
#define VERILATED_VNES_CORE_TOP___024ROOT_H_  // guard

#include "verilated.h"


class Vnes_core_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vnes_core_top___024root final {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(reset,0,0);
        VL_IN8(joy1_buttons,7,0);
        VL_IN8(joy2_buttons,7,0);
        VL_IN8(hud_mode,1,0);
        VL_IN8(hud_position,1,0);
        VL_IN8(hud_scale,0,0);
        VL_OUT8(color,5,0);
        VL_OUT8(hblank,0,0);
        VL_OUT8(vblank,0,0);
        VL_OUT8(hsync,0,0);
        VL_OUT8(vsync,0,0);
        VL_OUT8(hud_active,0,0);
        VL_OUT8(dbg_mr_int,0,0);
        VL_OUT8(dbg_mw_int,0,0);
        VL_OUT8(dbg_cpu_din,7,0);
        VL_OUT8(dbg_cpu_dout,7,0);
        VL_OUT8(dbg_nmi,0,0);
        VL_OUT8(dbg_pause_cpu,0,0);
        VL_OUT8(dbg_dma_active,0,0);
        VL_OUT8(dbg_dma_sprite_trigger,0,0);
        VL_OUT8(dbg_cpu_ce,0,0);
        VL_OUT8(dbg_reset_noSS,0,0);
        VL_OUT8(dbg_cpu_rnw,0,0);
        VL_OUT8(dbg_dma_spr_state,1,0);
        VL_OUT8(dbg_dma_get_ce,0,0);
        VL_OUT8(dbg_dma_put_ce,0,0);
        VL_OUT8(dbg_odd_or_even,0,0);
        VL_OUT8(dbg_en_bg,0,0);
        VL_OUT8(dbg_en_obj,0,0);
        VL_OUT8(dbg_vbl_en,0,0);
        VL_OUT8(dbg_nmi_occ,0,0);
        VL_OUT8(dbg_render_d,0,0);
        VL_OUT8(dbg_cpumem_read,0,0);
        VL_OUT8(dbg_cpumem_write,0,0);
        VL_OUT8(dbg_ppumem_read,0,0);
        VL_OUT8(dbg_ppumem_write,0,0);
        VL_OUT8(dbg_chr_to_ppu,7,0);
        VL_OUT8(dbg_ppumem_din,7,0);
        CData/*7:0*/ nes_core_top__DOT__joy1_shift;
        CData/*7:0*/ nes_core_top__DOT__joy2_shift;
        CData/*0:0*/ nes_core_top__DOT__last_joyclk0;
        CData/*0:0*/ nes_core_top__DOT__last_joyclk1;
        CData/*1:0*/ nes_core_top__DOT__joypad_clock;
        CData/*0:0*/ nes_core_top__DOT__cpumem_write;
        CData/*7:0*/ nes_core_top__DOT__cpumem_dout;
        CData/*0:0*/ nes_core_top__DOT__ppumem_read;
        CData/*0:0*/ nes_core_top__DOT__ppumem_write;
        CData/*7:0*/ nes_core_top__DOT__ppumem_dout;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__cpu_dout;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__odd_or_even;
        CData/*4:0*/ nes_core_top__DOT__nes_inst__DOT__div_cpu;
        CData/*2:0*/ nes_core_top__DOT__nes_inst__DOT__div_ppu;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__div_sys;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu_ce;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu_ce;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cart_pre;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__phi2;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__freeze_clocks;
        CData/*4:0*/ nes_core_top__DOT__nes_inst__DOT__faux_pixel_cnt;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__ppu_tick;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__last_sys_type;
        CData/*2:0*/ nes_core_top__DOT__nes_inst__DOT__cpu_tick_count;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__skip_ppu_cycle;
    };
    struct {
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__hold_reset;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__bootvector_flag;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu_reset;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__reset;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__reset_noSS;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__corepause_active;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__skip_pause_ce;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__corepause_delay;
        CData/*2:0*/ nes_core_top__DOT__nes_inst__DOT__div_ppu_pause;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu_ce_pause;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__render_ena;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT____Vcellinp__clockgen_pause__ce;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__nmi;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__internal_data_bus;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT____Vcellinp__cpu__DI;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT____Vcellinp__cpu__res_n;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__dma_aout_enable;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu_dma_request;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu_dma_ack;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__dma_data_bus;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__mr_int;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__mw_int;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__get_ce;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__put_ce;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT____Vcellinp__dma__sprite_trigger;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__joypad1_cs;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__joypad2_cs;
        CData/*2:0*/ nes_core_top__DOT__nes_inst__DOT__joy_out;
        CData/*2:0*/ nes_core_top__DOT__nes_inst__DOT__joy_latch;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu_cs;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__chr_write;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT____Vcellinp__ppu__write;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT____Vcellinp__ppu__read;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__prg_write;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__vram_ce;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__open_bus_data;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__clockgen_pause__DOT__end_of_line;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__clockgen_pause__DOT__is_pre_render;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__clockgen_pause__DOT__is_even_frame;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__clockgen_pause__DOT__skip_next;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__rdy_i;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__p;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__ad;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__dl;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__brk;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__alu_q;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__really_rdy;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n188;
        CData/*2:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n248;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n278;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n285;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n324;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n325;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n332;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n333;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n334;
        CData/*4:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n335;
        CData/*3:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n336;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n337;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n338;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n339;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n399;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n427;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n433;
    };
    struct {
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n438;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n483;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n530;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n531;
        CData/*2:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n598;
        CData/*2:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n603;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n620;
        CData/*2:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n631;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n681;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n682;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n683;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n685;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n686;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n687;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n688;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n741;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n749;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n843;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n846;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n894;
        CData/*2:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n898;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n899;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n900;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n901;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n902;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n916;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n917;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n918;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n919;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n921;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n922;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n928;
        CData/*2:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n929;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n930;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n931;
        CData/*4:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n932;
        CData/*3:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n933;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n934;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n935;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n936;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n937;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n939;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n940;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n941;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n942;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n943;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n944;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n945;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n946;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n947;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n948;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n949;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n950;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n951;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT____VdfgRegularize_heb0a8950_0_1;
        CData/*2:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2112;
        CData/*3:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2165;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2177;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2189;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2216;
        CData/*3:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2220;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2228;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2231;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2236;
    };
    struct {
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2254;
        CData/*3:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2257;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2265;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2268;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2272;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2293;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2301;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2307;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2325;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2333;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2336;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2380;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2392;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2452;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2476;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2479;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2717;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2726;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2728;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2731;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2734;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2737;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2740;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2746;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2749;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2875;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2881;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2885;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2936;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2942;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2945;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2948;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2954;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2956;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3017;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3063;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3073;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3076;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3079;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3116;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3123;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3126;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3130;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3194;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3201;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3204;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3207;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3210;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3216;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3218;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3241;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3248;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3251;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3253;
        CData/*2:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3289;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3382;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3396;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3399;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3402;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3405;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3408;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3414;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3417;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3478;
    };
    struct {
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3484;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3487;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3490;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3493;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3499;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3501;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3533;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3539;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3541;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3544;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3546;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3654;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3668;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3671;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3674;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3677;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3683;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3686;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3743;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3754;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3757;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3760;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3763;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3769;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3771;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3836;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3851;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3854;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3856;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3928;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3932;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3933;
        CData/*2:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3974;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3996;
        CData/*2:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n4017;
        CData/*4:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n4046;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n4056;
        CData/*4:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n4146;
        CData/*4:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n4178;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__dma__DOT__dmc_state;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__dma__DOT__spr_state;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__dma__DOT__sprite_dma_lastval;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__allow_us;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__lc_load;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__write;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__phi2_old;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__phi2_ce;
        CData/*4:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Enabled;
        CData/*3:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__TriSample;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__DmcIrq;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__IsDmcActive;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__ClkE;
        CData/*4:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__enabled_buffer;
        CData/*4:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__enabled_buffer_1;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT____Vcellinp__Squ1__write;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT____Vcellinp__Squ2__write;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT____Vcellinp__Tri__write;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT____Vcellinp__Noi__write;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT____Vcellinp__Dmc__write;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT____Vcellinp__frame_counter__write_ce;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ1__DOT__Duty;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ1__DOT__SweepEnable;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ1__DOT__SweepNegate;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ1__DOT__SweepReset;
    };
    struct {
        CData/*2:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ1__DOT__SweepPeriod;
        CData/*2:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ1__DOT__SweepDivider;
        CData/*2:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ1__DOT__SweepShift;
        CData/*2:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ1__DOT__SeqPos;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ1__DOT__ValidFreq;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ1__DOT__subunit_write;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ1__DOT__lc;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ1__DOT____Vcellinp__LenSq__len_clk;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ1__DOT__LenSq__DOT__lenunit__DOT__len_counter_int;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ1__DOT__LenSq__DOT__lenunit__DOT__halt;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ1__DOT__LenSq__DOT__lenunit__DOT__len_counter_next;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ1__DOT__LenSq__DOT__lenunit__DOT__lc_on_1;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ1__DOT__LenSq__DOT__lenunit__DOT__clear_next;
        CData/*3:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ1__DOT__EnvSq__DOT__env_count;
        CData/*3:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ1__DOT__EnvSq__DOT__env_vol;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ1__DOT__EnvSq__DOT__env_disabled;
        CData/*3:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ1__DOT__EnvSq__DOT__envunit__DOT__env_div;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ1__DOT__EnvSq__DOT__envunit__DOT__env_reload;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ1__DOT__EnvSq__DOT__envunit__DOT__env_loop;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ2__DOT__Duty;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ2__DOT__SweepEnable;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ2__DOT__SweepNegate;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ2__DOT__SweepReset;
        CData/*2:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ2__DOT__SweepPeriod;
        CData/*2:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ2__DOT__SweepDivider;
        CData/*2:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ2__DOT__SweepShift;
        CData/*2:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ2__DOT__SeqPos;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ2__DOT__ValidFreq;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ2__DOT__subunit_write;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ2__DOT__lc;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ2__DOT__LenSq__DOT__lenunit__DOT__len_counter_int;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ2__DOT__LenSq__DOT__lenunit__DOT__halt;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ2__DOT__LenSq__DOT__lenunit__DOT__len_counter_next;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ2__DOT__LenSq__DOT__lenunit__DOT__lc_on_1;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ2__DOT__LenSq__DOT__lenunit__DOT__clear_next;
        CData/*3:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ2__DOT__EnvSq__DOT__env_count;
        CData/*3:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ2__DOT__EnvSq__DOT__env_vol;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ2__DOT__EnvSq__DOT__env_disabled;
        CData/*3:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ2__DOT__EnvSq__DOT__envunit__DOT__env_div;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ2__DOT__EnvSq__DOT__envunit__DOT__env_reload;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ2__DOT__EnvSq__DOT__envunit__DOT__env_loop;
        CData/*4:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Tri__DOT__SeqPos;
        CData/*6:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Tri__DOT__LinCtrPeriod;
        CData/*6:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Tri__DOT__LinCtrPeriod_1;
        CData/*6:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Tri__DOT__LinCtr;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Tri__DOT__LinCtrl;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Tri__DOT__line_reload;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Tri__DOT__LinCtrZero;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Tri__DOT__lc;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Tri__DOT__subunit_write;
        CData/*3:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Tri__DOT__sample_latch;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Tri__DOT__LenTri__DOT__lenunit__DOT__len_counter_int;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Tri__DOT__LenTri__DOT__lenunit__DOT__halt;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Tri__DOT__LenTri__DOT__lenunit__DOT__len_counter_next;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Tri__DOT__LenTri__DOT__lenunit__DOT__lc_on_1;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Tri__DOT__LenTri__DOT__lenunit__DOT__clear_next;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Noi__DOT__ShortMode;
        CData/*3:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Noi__DOT__Period;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Noi__DOT__subunit_write;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Noi__DOT__lc;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Noi__DOT__noise_clock;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Noi__DOT__LenNoi__DOT__lenunit__DOT__len_counter_int;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Noi__DOT__LenNoi__DOT__lenunit__DOT__halt;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Noi__DOT__LenNoi__DOT__lenunit__DOT__len_counter_next;
    };
    struct {
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Noi__DOT__LenNoi__DOT__lenunit__DOT__lc_on_1;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Noi__DOT__LenNoi__DOT__lenunit__DOT__clear_next;
        CData/*3:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Noi__DOT__EnvNoi__DOT__env_count;
        CData/*3:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Noi__DOT__EnvNoi__DOT__env_vol;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Noi__DOT__EnvNoi__DOT__env_disabled;
        CData/*3:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Noi__DOT__EnvNoi__DOT__envunit__DOT__env_div;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Noi__DOT__EnvNoi__DOT__envunit__DOT__env_reload;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Noi__DOT__EnvNoi__DOT__envunit__DOT__env_loop;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Dmc__DOT__irq_enable;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Dmc__DOT__loop;
        CData/*3:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Dmc__DOT__frequency;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Dmc__DOT__sample_address;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Dmc__DOT__sample_length;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Dmc__DOT__sample_buffer;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Dmc__DOT__dmc_volume;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Dmc__DOT__dmc_volume_next;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Dmc__DOT__dmc_silence;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Dmc__DOT__have_buffer;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Dmc__DOT__sample_shift;
        CData/*2:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Dmc__DOT__dmc_bits;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Dmc__DOT__enable_1;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Dmc__DOT__enable_2;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Dmc__DOT__enable_3;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Dmc__DOT__dmc_clock;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__frame_counter__DOT__frame_interrupt_buffer;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__frame_counter__DOT__FrameInterrupt;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__frame_counter__DOT__set_irq;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__frame_counter__DOT__FrameSeqMode_2;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__frame_counter__DOT__frame_reset_2;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__frame_counter__DOT__w4017_1;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__frame_counter__DOT__w4017_2;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__frame_counter__DOT__DisableFrameInterrupt;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__frame_counter__DOT__FrameSeqMode;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__frame_counter__DOT__frm_d;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__obj_patt;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__obj_patt1;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__bg_patt;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__bg_patt1;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__obj_size;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__obj_size1;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__vbl_enable;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__clear;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__grayscale;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__playfield_clip;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__object_clip;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__in_range;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__nmi_occured;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__vram_latch;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__end_of_line;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__entering_vblank;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__is_pre_render_line;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__enable_playfield;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__enable_objects;
        CData/*2:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__re_sr;
        CData/*2:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__eo_sr;
        CData/*2:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__eb_sr;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__is_rendering;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__vram_a_byte;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT____Vcellinp__vram0__trigger_2007;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__in_visible_frame;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__bgp_en;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT____Vcellinp__spriteeval__oam_data_write;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT____Vcellinp__spriteeval__oam_addr_write;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_overflow;
    };
    struct {
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__obj0_on_line;
        CData/*3:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__spriteset_load;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_load_en;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT____Vcellinp__address_gen__temp;
        CData/*3:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_sr;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite0_hit_bg;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__spr0_hit;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__ALE;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__vram_din;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__vram_read_delayed;
        CData/*5:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__color2;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__pal_writes_valid;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__in_rendering_frame;
        CData/*4:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__write_2007_delayed;
        CData/*4:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__read_2007_delayed;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__clear_nmi;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__ppu_dbus;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__latched_dout;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__refresh_high;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__refresh_low;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__clock__DOT__is_even_frame;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__clock__DOT__skip_next;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__clock__DOT__hsync_period;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__clock__DOT__hblank_period;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__vram0__DOT__ppu_incr;
        CData/*2:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__vram0__DOT__vram_x;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__vram0__DOT__ppu_address_latch;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__vram0__DOT__write_shift;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__vram0__DOT__copy_hscroll;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__vram0__DOT__copy_vscroll;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__bg_painter__DOT__current_name_table;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__bg_painter__DOT__current_attribute_table;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__bg_painter__DOT__bg0;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__spriteeval__DOT__oam_dbus;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__spriteeval__DOT__oam_addr;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__spriteeval__DOT__oam_data;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__spriteeval__DOT__oam_secondary_ovr;
        CData/*5:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__spriteeval__DOT__oam_addr_ex;
        CData/*3:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__spriteeval__DOT__oam_secondary_row_ex;
        CData/*2:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__spriteeval__DOT__spr_counter;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__spriteeval__DOT__old_rendering;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__spriteeval__DOT__old_using_secondary;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__spriteeval__DOT__rendering;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__spriteeval__DOT__evaluating;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__spriteeval__DOT__oam_read_addr;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__spriteeval__DOT__using_secondary;
        CData/*4:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__spriteeval__DOT__oam_row_cur;
        CData/*4:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__spriteeval__DOT__oam_row_last;
        CData/*4:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__spriteeval__DOT__oam_secondary_addr;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__spriteeval__DOT__sprite0_curr;
        CData/*2:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__spriteeval__DOT__repeat_count;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__spriteeval__DOT__n_ovr;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__spriteeval__DOT__ex_ovr;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__spriteeval__DOT__oam_wr_enabled;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__spriteeval__DOT__oam_eval__DOT__eval_count;
        CData/*2:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__address_gen__DOT__count;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__address_gen__DOT__temp_tile;
        CData/*3:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__address_gen__DOT__temp_y;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__address_gen__DOT__flip_x;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__address_gen__DOT__flip_y;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__address_gen__DOT__load_y;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__address_gen__DOT__load_attr;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__address_gen__DOT__dummy_sprite;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite7__DOT__upper_color;
    };
    struct {
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite7__DOT__x_coord;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite7__DOT__pix1;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite7__DOT__pix2;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite7__DOT__aprio;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite7__DOT__active;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite6__DOT__upper_color;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite6__DOT__x_coord;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite6__DOT__pix1;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite6__DOT__pix2;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite6__DOT__aprio;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite6__DOT__active;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite5__DOT__upper_color;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite5__DOT__x_coord;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite5__DOT__pix1;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite5__DOT__pix2;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite5__DOT__aprio;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite5__DOT__active;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite4__DOT__upper_color;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite4__DOT__x_coord;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite4__DOT__pix1;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite4__DOT__pix2;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite4__DOT__aprio;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite4__DOT__active;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite3__DOT__upper_color;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite3__DOT__x_coord;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite3__DOT__pix1;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite3__DOT__pix2;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite3__DOT__aprio;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite3__DOT__active;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite2__DOT__upper_color;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite2__DOT__x_coord;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite2__DOT__pix1;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite2__DOT__pix2;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite2__DOT__aprio;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite2__DOT__active;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite1__DOT__upper_color;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite1__DOT__x_coord;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite1__DOT__pix1;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite1__DOT__pix2;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite1__DOT__aprio;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite1__DOT__active;
        CData/*1:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite0__DOT__upper_color;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite0__DOT__x_coord;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite0__DOT__pix1;
        CData/*7:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite0__DOT__pix2;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite0__DOT__aprio;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__sprite0__DOT__active;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__palette_ram__DOT__corrupting;
        CData/*4:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__palette_ram__DOT__addr2;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__palette_ram__DOT__old_rendering;
        CData/*0:0*/ nes_core_top__DOT__nes_inst__DOT__multi_mapper__DOT____VdfgExtracted_hca5e3773__0;
        CData/*0:0*/ __VdfgRegularize_hebeb780c_0_107;
        CData/*0:0*/ __VdfgRegularize_hebeb780c_0_108;
        CData/*0:0*/ __VdfgRegularize_hebeb780c_0_109;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VstlPhaseResult;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __VicoPhaseResult;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__nes_core_top__DOT__nes_inst__DOT____Vcellinp__cpu__res_n__0;
        CData/*0:0*/ __VactPhaseResult;
        CData/*0:0*/ __VnbaPhaseResult;
        VL_OUT16(cycle,8,0);
        VL_OUT16(scanline,8,0);
    };
    struct {
        VL_OUT16(sample,15,0);
        VL_OUT16(dbg_cpu_addr,15,0);
        VL_OUT16(dbg_cpu_pc,15,0);
        SData/*8:0*/ nes_core_top__DOT__nes_inst__DOT__cycle_paused;
        SData/*8:0*/ nes_core_top__DOT__nes_inst__DOT__scanline_paused;
        SData/*15:0*/ nes_core_top__DOT__nes_inst__DOT__apu_dma_addr;
        SData/*15:0*/ nes_core_top__DOT__nes_inst__DOT__addr;
        SData/*8:0*/ nes_core_top__DOT__nes_inst__DOT__ppu_cycle;
        SData/*8:0*/ nes_core_top__DOT__nes_inst__DOT__scanline_ppu;
        SData/*8:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__pcadder;
        SData/*15:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n225;
        SData/*15:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n326;
        SData/*15:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n328;
        SData/*15:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n540;
        SData/*15:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n542;
        SData/*15:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n544;
        SData/*8:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n645;
        SData/*8:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n684;
        SData/*10:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n747;
        SData/*15:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n913;
        SData/*15:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n914;
        SData/*15:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n915;
        SData/*8:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n920;
        SData/*15:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n923;
        SData/*15:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n924;
        SData/*15:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n2606;
        SData/*13:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__mcode__DOT__n3891;
        SData/*15:0*/ nes_core_top__DOT__nes_inst__DOT__dma__DOT__sprite_dma_addr;
        SData/*8:0*/ nes_core_top__DOT__nes_inst__DOT__dma__DOT__new_sprite_dma_addr;
        SData/*10:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ1__DOT__Period;
        SData/*11:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ1__DOT__TimerCtr;
        SData/*11:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ1__DOT__NewSweepPeriod;
        SData/*10:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ2__DOT__Period;
        SData/*11:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ2__DOT__TimerCtr;
        SData/*11:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Squ2__DOT__NewSweepPeriod;
        SData/*10:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Tri__DOT__Period;
        SData/*10:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Tri__DOT__applied_period;
        SData/*10:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Tri__DOT__TimerCtr;
        SData/*14:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Noi__DOT__Shift;
        SData/*10:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Noi__DOT__noise_timer;
        SData/*11:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Dmc__DOT__bytes_remaining;
        SData/*8:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__Dmc__DOT__dmc_lsfr;
        SData/*14:0*/ nes_core_top__DOT__nes_inst__DOT__apu__DOT__frame_counter__DOT__frame;
        SData/*13:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__vram_a;
        SData/*8:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__scanline_nopr;
        SData/*14:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__vram0__DOT__vram_v;
        SData/*14:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__vram0__DOT__vram_t;
        SData/*14:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__vram0__DOT__vram_t_mask;
        SData/*15:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__bg_painter__DOT__playfield_pipe_1;
        SData/*15:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__bg_painter__DOT__playfield_pipe_2;
        SData/*8:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__bg_painter__DOT__playfield_pipe_3;
        SData/*8:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__bg_painter__DOT__playfield_pipe_4;
        SData/*8:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__spriteeval__DOT__oam_eval__DOT__last_y;
        SData/*8:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__spriteeval__DOT__oam_eval__DOT__last_tile;
        SData/*8:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__spriteeval__DOT__oam_eval__DOT__last_attr;
        SData/*13:0*/ nes_core_top__DOT__nes_inst__DOT__multi_mapper__DOT__chr_ain;
        VL_IN(prg_mask_in,20,0);
        VL_IN(chr_mask_in,19,0);
        VL_OUT(hud_pixel,23,0);
        VL_OUT(dbg_cpumem_addr,24,0);
        VL_OUT(dbg_ppumem_addr,21,0);
        IData/*24:0*/ nes_core_top__DOT__nes_inst__DOT__prg_linaddr;
        IData/*21:0*/ nes_core_top__DOT__nes_inst__DOT__chr_linaddr;
        IData/*23:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__n774;
    };
    struct {
        IData/*26:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__spriteset_load_in;
        IData/*23:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__decay_high;
        IData/*23:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__decay_low;
        IData/*26:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__load_out7;
        IData/*26:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__load_out6;
        IData/*26:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__load_out5;
        IData/*26:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__load_out4;
        IData/*26:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__load_out3;
        IData/*26:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__load_out2;
        IData/*26:0*/ nes_core_top__DOT__nes_inst__DOT__ppu__DOT__sprite_gen__DOT__load_out1;
        IData/*31:0*/ __VactIterCount;
        VL_IN64(mapper_flags_in,63,0);
        VL_OUT64(dbg_cpu_regs,63,0);
        QData/*63:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__ireg_savestate_t80_1__DOT__dout_buffer;
        QData/*63:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__ireg_savestate_t80_1__DOT__n1289;
        QData/*63:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__ireg_savestate_t80_2__DOT__dout_buffer;
        QData/*63:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__ireg_savestate_t80_2__DOT__n1627;
        QData/*63:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__ireg_savestate_t80_3__DOT__dout_buffer;
        QData/*63:0*/ nes_core_top__DOT__nes_inst__DOT__cpu__DOT__cpu_impl__DOT__ireg_savestate_t80_3__DOT__n1965;
        VlUnpacked<CData/*7:0*/, 32768> nes_core_top__DOT__prg_rom;
        VlUnpacked<CData/*7:0*/, 8192> nes_core_top__DOT__chr_rom;
        VlUnpacked<CData/*7:0*/, 2048> nes_core_top__DOT__cpu_ram;
        VlUnpacked<CData/*7:0*/, 2048> nes_core_top__DOT__ciram;
        VlUnpacked<CData/*7:0*/, 2048> nes_core_top__DOT__cart_ram;
        VlUnpacked<CData/*7:0*/, 32> nes_core_top__DOT__nes_inst__DOT__apu__DOT__len_counter_lut;
        VlUnpacked<SData/*10:0*/, 16> nes_core_top__DOT__nes_inst__DOT__apu__DOT__Noi__DOT__noise_ntsc_lut;
        VlUnpacked<SData/*8:0*/, 16> nes_core_top__DOT__nes_inst__DOT__apu__DOT__Dmc__DOT__ntsc_pitch_lut;
        VlUnpacked<SData/*15:0*/, 32> nes_core_top__DOT__nes_inst__DOT__apu__DOT__mixer__DOT__pulse_lut;
        VlUnpacked<CData/*5:0*/, 16> nes_core_top__DOT__nes_inst__DOT__apu__DOT__mixer__DOT__tri_lut;
        VlUnpacked<CData/*5:0*/, 16> nes_core_top__DOT__nes_inst__DOT__apu__DOT__mixer__DOT__noise_lut;
        VlUnpacked<CData/*7:0*/, 128> nes_core_top__DOT__nes_inst__DOT__apu__DOT__mixer__DOT__dmc_lut;
        VlUnpacked<SData/*15:0*/, 512> nes_core_top__DOT__nes_inst__DOT__apu__DOT__mixer__DOT__mix_lut;
        VlUnpacked<CData/*5:0*/, 4> nes_core_top__DOT__nes_inst__DOT__ppu__DOT__color_pipe;
        VlUnpacked<CData/*7:0*/, 64> nes_core_top__DOT__nes_inst__DOT__ppu__DOT__spriteeval__DOT__oam_temp;
        VlUnpacked<CData/*7:0*/, 256> nes_core_top__DOT__nes_inst__DOT__ppu__DOT__spriteeval__DOT__oam;
        VlUnpacked<QData/*63:0*/, 4> nes_core_top__DOT__nes_inst__DOT__ppu__DOT__palette_ram__DOT__SS_PAL;
        VlUnpacked<CData/*5:0*/, 32> nes_core_top__DOT__nes_inst__DOT__ppu__DOT__palette_ram__DOT__palette;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
    };

    // INTERNAL VARIABLES
    Vnes_core_top__Syms* vlSymsp;
    const char* vlNamep;

    // CONSTRUCTORS
    Vnes_core_top___024root(Vnes_core_top__Syms* symsp, const char* namep);
    ~Vnes_core_top___024root();
    VL_UNCOPYABLE(Vnes_core_top___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
